# Generated by Django 4.2.5 on 2023-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_photo_user_avator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='language',
            new_name='language_A',
        ),
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
